C0:
  - [0.0, 0.0, 0.0, 0.0, 0.0]   # platform 0 (LNP)
  - [0.0, 0.0, 0.0, 0.0, 0.0]   # platform 1 (EV)

U0:
  -  # platform 0
    - [0.0, 0.0, 0.0, 0.0]   # plasma
    - [0.0, 0.0, 0.0, 0.0]   # liver
    - [0.0, 0.0, 0.0, 0.0]   # periphery
    - [0.0, 0.0, 0.0, 0.0]   # CNS
    - [0.0, 0.0, 0.0, 0.0]   # CSF
  -  # platform 1
    - [0.0, 0.0, 0.0, 0.0]
    - [0.0, 0.0, 0.0, 0.0]
    - [0.0, 0.0, 0.0, 0.0]
    - [0.0, 0.0, 0.0, 0.0]
    - [0.0, 0.0, 0.0, 0.0]

m0:       [0.0, 0.0, 0.0, 0.0]
P_tot0:   [0.0, 0.0, 0.0, 0.0]
P_peri0:  [0.0, 0.0, 0.0, 0.0]

C26_plasma0: 1.0
C26_CNS0: 1.0
Inflamm0: 0.0
AxonInjury0: 0.0

Scytokine0: 0.0
S_ALT0: 0.0
S_AST0: 0.0

ADA0: [0.0, 0.0]
